### ISSUE TITLE
The bang is really helpful if to be improved

### ISSUE THREAD

**Issue by chenxofhit** [freesme/barrage-bang#1]
In my classes, I usually talk in front of the desk, the students sit there listening to me.  If the barrage can instantly appear in front of the screen, i.e. crossing the PowerPoint full screen, it will help me understand the questions of the students. I hope you can catch me and make improvements to this repository.

**Comment by freesme** [comment]
barrage-bang barrage functions rely mainly on [jquery. Barrager. Js](https://github.com/yaseng/jquery.barrager.js) .If there is an urgent need for use this can be extended using jquery.barrager.js. 
Mobile client is currently under development. 
Welcome to provide a detailed list so that we can support it in the future.
